name: Workflow1

# Controls when the action will run. We only want that this action to happens when
# we open a pull request that points to main or Staging
on:
  push:
      branches:
        - 'main'
  # This would make this workflow reusable. That is, that any other repo
  # can easily call and use this workflow in their own repositories.
  # --------------------------------------------------------------------- #
  # To use this Workflow, you need to specify this line on your job:      #
  # uses: valiot/ValueChainOS-Queues/.github/workflows/ci_tools.yml@main  #
  # --------------------------------------------------------------------- #
  workflow_call:


jobs:
  run_action:
    name: Run the action 1
    runs-on: ubuntu-latest
      - name: Action 1
        uses: CarlosDBP/hello-github-actions/actions/action@main
      